<html>
    <head>
        <title>XSS Tours</title>
        <?php include('../templates/_header.php'); ?>
    </head>
    <body>
        <h1>Welcome to XSS Tour</h1>
        <div>Find the XSS.</div>

        <a href="/level/1">Level1</a><br />
        <a href="/level/2">Level2</a><br />
        <a href="/level/3">Level3</a><br />
        <a href="/level/4">Level4</a><br />
        <a href="/level/5">Level5</a>
    </body>
</html>
