<html>
    <head>
        <meta charset="utf-8"/>
        <title>XSS Tours</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>Welcome to XSS Tour</h1>
        <div>Find the XSS.</div>

        <a href="/level/1">Level1</a><br />
        <a href="/level/2">Level2</a><br />
        <a href="/level/3">Level3</a><br />
        <a href="/level/4">Level4</a>
    </body>
</html>
