<html>
    <head>
        <title>XSS Tours - Level 5</title>
        <?php include('../templates/_header.php'); ?>
    </head>

    <body>
        <div class="container">
            <h1>Level5</h1>

            <h3>Mission: exec "alert('xss')"</h3>

            <?php include('../templates/_success.php'); ?>

            <p>
                This level contains the Reflection XSS<br />
            </p>

            <a href="/">Back to home</a>
        </div>
    </body>
</html>
