<html>
    <head>
        <title>XSS Tours - Level 3</title>
        <?php include('../templates/_header.php'); ?>
    </head>

    <script>
        function escape(string) {
            return string
                .replace(/&/g, '&amp;')
                .replace(/</g, '&lt;')
                .replace(/>/g, '&gt;')
                .replace(/"/g, '&quot;')
                .replace(/'/g, '&#039;');
        }

        var callName = function (name) {
            document.getElementById('call-space').innerText = 'I love you, ' + escape(name) + '!!';
        };
    </script>

    <body>
        <div class="container">
            <h1>Level3</h1>

            <h3>Mission: exec "alert('xss')"</h3>

            <p>
                This level contains the standard XSS(Reflection XSS).<br />
                You can add <mark>name</mark> GET query string and you can make your original button calling your name!!.<br />
                Try to access <a href="?name=YourName">/level/3/name=YourName</a><br />
                <b>Notice: The application escape <mark>&gt;</mark>, <mark>&lt;</mark>, single quotes and double quotes character.</b>
            </p>

            <?php include('../templates/_success.php'); ?>

            <h2>
                Hello, <?php echo e($getName) ?>. <br/>
                I will call your name. Let's click button!
            </h2>
            <p>
                <button type="button" class="btn btn-info" onclick="callName('<?php echo e($getName); ?>');">Call me please</button>
            </p>

            <h4 id="call-space"></h4>

            <a href="/">Back to home</a>
        </div>
    </body>
</html>
