<html>
    <head>
        <title>XSS Tours - Level 4</title>
        <?php include('../templates/_header.php'); ?>
    </head>

    <script>
        function escape(string) {
            return string
                .replace(/&/g, '&amp;')
                .replace(/</g, '&lt;')
                .replace(/>/g, '&gt;')
                .replace(/"/g, '&quot;')
                .replace(/'/g, '&#039;');
        }

        function getRedirectPageUrl(){
            var url = location.hash.substring(1);

            try {
                if (url.length === 0) return "/";
                url = decodeURIComponent(url);
                if (!url.match( /^https?:\/\// )) return "/";
            } catch (e) {
                console.log(e);
                document.getElementById('error-space').innerHTML =
                    '<p class="bg-danger" style="padding:15px; margin-top: 15px">invalid url</p>';
            }

            return url;
        }

        function redirect() {
            var url = getRedirectPageUrl();
            location.href = url;
        }

        function updateTargetUrl() {
            document.getElementById('target-url').innerHTML = escape(location.hash.substring(1));
        }

        window.onload = updateTargetUrl;

    </script>

    <body>
        <div class="container">
            <h1>Level4</h1>

            <h3>Mission: exec "alert('xss')"</h3>

            <p>
                This level contains the DOM Based XSS<br />
                You can specify redirect URL by adding URL hash.<br />
                Then redirect button avalaible.<br />
                For example, you access <mark>/level/4#http://sota1235.com</mark>, you can redirect to <mark>http://sota1235.com</mark> when clicking button.<br />
                <b>But the url must be HTTP or HTTPS scheme.</b>
            </p>

            <?php include('../templates/_success.php'); ?>

            <h2>
                You will redirect to <span id="target-url"></span> by clicking button.
            </h2>
            <button type="button" class="btn btn-info" onclick="redirect()">Redirect</button><br />
            <div id="error-space"></div><br />

            <a href="/">Back to home</a>
        </div>
    </body>
</html>
