<html>
    <head>
        <title>XSS Tours - Level 5</title>
        <?php include('../templates/_header.php'); ?>
    </head>

    <body>
        <div class="container">
            <h1>Level5</h1>

            <h3>Mission: exec "alert('xss')"</h3>

            <p>
                This level contains the Reflection XSS<br />
                You can enter your name on text box.<br />
                If you submit the text, the application is you in the greeting :)<br/>
                Let's try it!!<br />
                <b>Notice: The application replace 'script' and 'alert' character.</b>
            </p>

            <?php include('../templates/_success.php'); ?>

            <h2>What you name?</h2>
            <form method="POST" action="/level/5">
                <input type="text" name="name" value="<?php echo $getName ?>">
                <input type="submit" value="Submit">
            </form>

            <?php if (isset($isPost)) {?>
                <h2>Hello, <?php echo $getName; ?></h2>
            <?php } ?>

            <a href="/">Back to home</a>
        </div>
    </body>
</html>
