<html>
    <head>
        <title>XSS Tours - Level 4</title>
        <?php include('../templates/_header.php'); ?>
    </head>

    <script>
        function escape(string) {
            return string
                .replace(/&/g, '&amp;')
                .replace(/</g, '&lt;')
                .replace(/>/g, '&gt;')
                .replace(/"/g, '&quot;')
                .replace(/'/g, '&#039;');
        }

        function getRedirectPageUrl(){
            var url = location.hash.substring(1);

            try {
                if (url.length === 0) return "/";
                url = decodeURIComponent(url);
                if (!url.match( /^https?:\/\// )) return "/";
            } catch (e) {
                document.getElementById('error-space').innerText = 'invalid url';
            }

            return url;
        }

        function redirect() {
            var url = getRedirectPageUrl();
            location.href = url;
        }

        function updateTargetUrl() {
            console.log(escape(location.hash.substring(1)));

            document.getElementById('target-url').innerHTML = escape(location.hash.substring(1));
        }

        window.onload = updateTargetUrl;

    </script>

    <body>
        <h1>Level4</h1>

        <h3>Mission: exec "alert('xss')"</h3>

        <p>
            This level contains the DOM Based XSS<br />
            You can specify redirect URL by adding URL hash.<br />
            Then redirect button avalaible.<br />
            For example, you access '/level/4#http://sota1235.com', you can redirect to 'http://sota1235.com' when clicking button.<br />
            But the url must be HTTP or HTTPS scheme.
        </p>

        <h2>
            You will redirect to <span id="target-url"></span> by clicking button.
        </h2>
        <button onclick="redirect()">Redirect</button><br />
        <div id="error-space"></div><br />

        <a href="/">Back to home</a>
    </body>
</html>
