<html>
    <head>
        <meta charset="utf-8"/>
        <title>XSS Tours - Level 2</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>Level2</h1>

        <p>
            This level contains the standard XSS(Reflection XSS).<br />
            You can add 'name' GET query string.<br />
            Try to access <a href="?name=YourName">/level/2/name=YourName</a><br />
            <b>Notice: The application replace 'script' character.</b>
        </p>

        <h2>Hello, <?php echo $getName; ?></h2>

        <a href="/">Back to home</a>
    </body>
</html>
