<html>
    <head>
        <title>XSS Tours - Level 1</title>
        <?php include('../templates/_header.php'); ?>
    </head>
    <body>
        <div class="container">
            <h1>Level1</h1>

            <h3>Mission: exec "alert('xss')"</h3>

            <p>
                This level contains the standard XSS(Reflection XSS).<br />
                You can add 'name' GET query string.<br />
                Try to access <a href="?name=YourName">/level/1/name=YourName</a>
            </p>

            <h2>Hello, <?php echo $getName ?></h2>

            <a href="/">Back to home</a>
        </div>
    </body>
</html>
